export const LOAD_CANDIDATES = 'LOAD_CANDIDATES';
export const ADD_CANDIDATE = 'ADD_CANDIDATE';
export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE';
export const DELETE_CANDIDATE = 'DELETE_CANDIDATE';
